In [3]:
import torch

In [13]:
tensor0d = torch.tensor(1)
tensor1d = torch.tensor([1,2])
tensor2d = torch.tensor([[1,2,3],[4,5,6]])
tensor3d = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])

In [14]:
print(tensor2d)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [30]:
print(tensor2d.shape)
print(tensor2d.T)
print(tensor2d.T.shape)
print(tensor2d.reshape([6,1]))
print(tensor2d.reshape([1,6]))
print(tensor2d.view([3,2]))
print(tensor2d.view([2,3]))

torch.Size([2, 3])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([3, 2])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [31]:
print(tensor3d.shape)
print(tensor3d.T)

torch.Size([2, 2, 2])
tensor([[[1, 5],
         [3, 7]],

        [[2, 6],
         [4, 8]]])


In [33]:
print(tensor2d.matmul(tensor2d.T))
print(tensor2d.T.matmul(tensor2d))

tensor([[14, 32],
        [32, 77]])
tensor([[17, 22, 27],
        [22, 29, 36],
        [27, 36, 45]])


In [36]:
print(tensor2d.to(torch.qint32))

RuntimeError: empty_strided not supported on quantized tensors yet see https://github.com/pytorch/pytorch/issues/74540