In [3]:
import torch

In [5]:
import torch.nn.functional as F

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([1.2])
b = torch.tensor([0.0])

z1 = x1 * w1 + b
a = torch.sigmoid(z1)
loss = F.binary_cross_entropy(a, y)

In [6]:
print(a, y, loss)

tensor([0.7892]) tensor([1.]) tensor(0.2368)


In [13]:
import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)

z1 = x1 * w1 + b
a = torch.sigmoid(z1)
loss = F.binary_cross_entropy(a, y)

grad_L_w1 =  grad(loss, w1, retain_graph = True)
grad_L_b =  grad(loss, b, retain_graph = True)

In [14]:
print(grad_L_w1)
print(grad_L_b)

(tensor([-0.0898]),)
(tensor([-0.0817]),)


In [15]:
loss.backward()
print(w1.grad)
print(b.grad)

tensor([-0.0898])
tensor([-0.0817])
